Traceback (most recent call last):
  File "/Users/mmccull/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/mmccull/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/mmccull/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/mmccull/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/mmccull/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/mmccull/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/mmccull/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/mmccull/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
    
fig, ax = plt.subplots(3,3,figsize=(12,12),dpi= 80, facecolor='w', edgecolor='k',subplot_kw={'projection': '3d'}) 
for l in range(3):
    for n in range(1,4):
        plot_particle_in_sphere_wf_r_theta(n,l,0,ax[l,n-1])
plt.show();
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-5-07d843e1e8c3>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0;32mfor[0m [0ml[0m [0;32min[0m [0mrange[0m[0;34m([0m[0;36m3[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m     [0;32mfor[0m [0mn[0m [0;32min[0m [0mrange[0m[0;34m([0m[0;36m1[0m[0;34m,[0m[0;36m4[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m         [0mplot_particle_in_sphere_wf_r_theta[0m[0;34m([0m[0mn[0m[0;34m,[0m[0ml[0m[0;34m,[0m[0;36m0[0m[0;34m,[0m[0max[0m[0;34m[[0m[0ml[0m[0;34m,[0m[0mn[0m[0;34m-[0m[0;36m1[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0mplt[0m[0;34m.[0m[0mshow[0m[0;34m([0m[0;34m)[0m[0;34m;[0m[0;34m[0m[0;34m[0m[0m

[0;32m<ipython-input-4-f0568183da47>[0m in [0;36mplot_particle_in_sphere_wf_r_theta[0;34m(n, l, m, ax_obj, r, theta, phi)[0m
[1;32m     53[0m     [0max_obj[0m[0;34m.[0m[0mset_title[0m[0;34m([0m[0;34mrf'$n={n},l={l},m={m}$'[0m[0;34m,[0m [0mfontsize[0m[0;34m=[0m[0;36m18[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     54[0m     [0max_obj[0m[0;34m.[0m[0mscatter3D[0m[0;34m([0m[0mx[0m[0;34m,[0m[0my[0m[0;34m,[0m[0mz[0m[0;34m,[0m[0mc[0m[0;34m=[0m[0mwf[0m[0;34m,[0m [0mvmin[0m[0;34m=[0m[0;34m-[0m[0;36m0.2[0m[0;34m,[0m [0mvmax[0m[0;34m=[0m[0;36m0.2[0m[0;34m,[0m[0malpha[0m[0;34m=[0m[0;36m0.25[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 55[0;31m     [0max_obj[0m[0;34m.[0m[0mset_box_aspect[0m[0;34m([0m[0;34m([0m[0;36m100[0m[0;34m,[0m[0;36m100[0m[0;34m,[0m[0;36m100[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     56[0m     [0;31m# xy countour[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     57[0m     [0;31m#R, PHI = np.meshgrid(r, phi)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: 'Axes3DSubplot' object has no attribute 'set_box_aspect'
AttributeError: 'Axes3DSubplot' object has no attribute 'set_box_aspect'

